# Generated by Django 5.1.1 on 2025-01-15 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_friend_created_at_friend_updated_at_friend_user1_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='friend',
            unique_together=set(),
        ),
    ]
